# Defines four organizations
#  - Orderer organization
#  - merkaba
#  - socio1
#  - Expo
##### Orderer for merkaba
OrdererOrgs:
  - Name: Orderer
    Domain: merkaba.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      
#### Peers for merkaba
PeerOrgs:
  # Peer configuration for merkaba
  - Name: Merkaba
    Domain: merkaba.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer1.merkaba.com
        CommonName: peer1.merkaba.com
    Users:
      Count: 1

  # Peer configuration for socio1
  - Name: Socio1
    Domain: socio1.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer1.socio1.com
        CommonName: peer1.socio1.com
    Users:
      Count: 1

  # # Peer configuration for socio1
  # - Name: Expo
  #   Domain: expo.com
  #   EnableNodeOUs: true
  #   Specs:
  #     - Hostname: peer1.expo.com
  #       CommonName: peer1.expo.com
  #   Users:
  #     Count: 1


      