# Compose file for launching the test setup with
# a Peer for merkaba and a Peer for socio1

version: '2.4'

networks:
  cooperativa:

# Storage outside the containers
volumes:
  data-orderer.merkaba.com:

services:

  # Orderer service
  orderer.merkaba.com:
    container_name: orderer.merkaba.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    command: orderer
    # Override environment variables for orderer in this section
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=ERROR
      # Add the environment properties to ENABLE TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/tls/ca.crt]
    # Host folder mappings
    volumes:
    # Folder with genesis block
    - ./:/var/hyperledger/config
    # Map the folder with MSP for orderer
    - ../crypto-config/ordererOrganizations/merkaba.com/orderers/orderer.merkaba.com/msp:/var/hyperledger/msp
    # Added to support the TLS setup
    - ../crypto-config/ordererOrganizations/merkaba.com/orderers/orderer.merkaba.com/tls:/var/hyperledger/tls
    - data-orderer.merkaba.com:/var/ledger
    ports:
      - 7050:7050
    networks:
      - cooperativa