version: '2.4'

networks:
  airline:

services:

  ca_acme:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.acme.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/acme:/etc/hyperledger/fabric-ca-server
    container_name: ca.acme.com
    hostname: ca.acme.com
    networks:
      - airline